# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ee81858be4b2d6c2202f7daefbebf81585b98691f55aba88de963b9309d1b1d0367f6a61b067ea0b1863606e0a18f49735cc865c9f3b8c31a4bd00c8014fe66

test:
  secret_key_base: 3b947fa03a8462524235a6751b575ff7797531fbff83b202ff71f6fd14d4ad9126d7cfaccb1518c2459f57a93a80ab73e7b3e8648796006c995a2243a186ce94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
